version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=biodex_db
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - API_VERSION=0.1.0
    depends_on:
      - mongodb
    networks:
      - biodex-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - biodex-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  frontend:
    build: ./frontend
    ports:
      - "8001:8001"
    depends_on:
      - backend
    networks:
      - biodex-network
    restart: unless-stopped

networks:
  biodex-network:
    driver: bridge

volumes:
  mongodb-data:
